### ISSUE TITLE
Update version of pyclean on PyPI

### ISSUE THREAD

**Issue by nth10sd** [bittner/pyclean#17]
`pip install pyclean` seems to get the Python 2 version. The [Download files](https://pypi.org/project/pyclean/#files) link on PyPI seems to show the latest version for py2 for Mar 22, 2019.

I get errors involving `except (IOError, OSError), e:` on Python 3.7 and 3.8 with version 1.0.0. A new build may be needed to be pushed to PyPI.

**Comment by bittner** [comment]
Pyclean is currently just a wrapper around the Debian scripts (as described in and linked to from the [README](https://github.com/bittner/pyclean#debian)).

Version 1.0.0 installs [three direct aliases](https://github.com/bittner/pyclean/blob/1.0.0/setup.py#L47-L49) to the original scripts: `pyclean` (for Python 2), `py3clean` (for Python 3), `pypyclean` (for PyPy3). You may want to try to use them directly to match your Python version.

Note that the plan are to get rid of the heritage (in some ideally backward compatible way) and have just a single implementation. This is what is currently the [modern](https://github.com/bittner/pyclean/blob/master/pyclean/modern.py) module.

**Comment by nth10sd** [comment]
It seems like these scripts are Debian/Ubuntu-specific. I'm on Gentoo, and was hoping for a PyPI version, thought this was the answer. :( Anyway, closing this out, thanks!

**Comment by bittner** [comment]
I have released v2.0.0, which should now work on any platform supported by Python3.

Can you try whether it does what you expect?

**Comment by nth10sd** [comment]
Yes, it does seem to work as expected, thank you!
