### ISSUE TITLE
Ignore (special) hidden directories by default

### ISSUE THREAD

**Issue by bittner** [bittner/pyclean#21]
Currently, `pyclean` recurses into all directories, be they special, hidden folders (e.g. `.git`, `.tox`) or not.

This behavior is probably undesired (especially the folders for Tox and Git might suffer from that), hence we should either ignore a list of "special" folders or any hidden (Unix) folder in general. The latter would affect folder names starting with a period (`.`).

For both ease of maintenance and user experience I'm leaning towards the generic solution. Are there any reasons against it?

**Comment by nicpayne713** [comment]
Any word on this? I'd love to be able to tell `pyclean` to ignore my `.venv` folder as I manage virtual environments in each of my local project directories

**Comment by bittner** [comment]
Thanks for your input!

If you want to give it a shot feel free to open a PR.
