### ISSUE TITLE
Add an option to only hide __pycache__ *.pyc files

### ISSUE THREAD

**Issue by fmalina** [bittner/pyclean#22]
Windows and OS X filesystems support hidden flag on files and directories, which is relevant to pyclean.

For implementation completeness consider supporting an option to add this flag as per https://stackoverflow.com/a/28365204/90263

with e.g.: 

    pyclean . --hideonly

**Comment by fmalina** [comment]
On OS X

    find . -name '__pycache__' -exec chflags hidden {} \;

**Comment by bittner** [comment]
Hmmm, that's interesting. I never thought anyone would want to _hide_ the Python bytecode files. :thinking: 

I too think that you shouldn't delete `.pyc` files in your production environment. But why on earth do you think that for development module execution performance is more important that executing non-existing or deleted modules by error? (Think this, you're developing a module and rename the source file, a reference of your code still uses the old name, which happily finds the related `.pyc` file and runs it; I think that happened to me in the past.)

Personally, I envision PyClean for development. To restore a clean state, remove build artifacts, etc. – Everyone's free to use it for whatever they want, of course.

I'm totally open to a pull request if you want to try one. Please use Python code for all system calls, though. We shouldn't depend on external binaries, neither on macOS nor on Windows.

**Comment by bittner** [comment]
I'm tempted to close this issue as "wont do" for the reasons explained above.

If there is any reason to still address this issue please continue the discussion here, or in a pull request that you create.

Thank you for your understanding!

**Comment by fmalina** [comment]
Lol, that never happened to me, I want to test it 😂 that would drive me nuts. I am a bit less OCD these days and not bothered hiding anymore.
Py3 __pycache__ is way less obtrusive than Py2 *.pyc files. I also think --hideonly option is silly. Separate 'pychide' command would be preferrable
