### ISSUE TITLE
Run test_modern.py by itself with tox

### ISSUE THREAD

**Issue by dave-kennedy** [bittner/pyclean#27]
I wanted to take a stab at this roadmap item:

> 3. Add additional CLI options to delete debris from builds, testing and packaging (build/, .cache/, dist/, .pytest_cache/, .tox/ and free-form targets).

I modified some of the tests in test_modern.py and attempted to run just the tests in that module like so:

```
$ tox -e py39 -- tests/test_modern.py
```

This ran all the tests, so I added `{posargs}` to the pytest command in tox.ini:

```
commands = pytest {posargs}
```

Now, running the same command produces an error:

```
$ tox -e py39 -- tests/test_modern.py
GLOB sdist-make: /Users/dave.kennedy/Code/pyclean/setup.py
py39 inst-nodeps: /Users/dave.kennedy/Code/pyclean/.tox/.tmp/package/1/pyclean-2.0.0.zip
py39 installed: attrs==20.3.0,cli-test-helpers==1.0.1,iniconfig==1.1.1,packaging==20.9,pluggy==0.13.1,py==1.10.0,pyclean @ file:///Users/dave.kennedy/Code/pyclean/.tox/.tmp/package/1/pyclean-2.0.0.zip,pyparsing==2.4.7,pytest==6.2.2,toml==0.10.2
py39 run-test-pre: PYTHONHASHSEED='388407112'
py39 run-test: commands[0] | pytest tests/test_modern.py
================================================= test session starts ==================================================
platform darwin -- Python 3.9.1, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /Users/dave.kennedy/Code/pyclean/.tox/py39/bin/python
cachedir: .tox/py39/.pytest_cache
rootdir: /Users/dave.kennedy/Code/pyclean, configfile: tox.ini
collected 0 items / 1 error                                                                                            

======================================================== ERRORS ========================================================
________________________________________ ERROR collecting tests/test_modern.py _________________________________________
tests/test_modern.py:50: in <module>
    ???
E   AttributeError: module 'pyclean' has no attribute 'modern'
```

The offending line is here:

```
@patch.object(pyclean.modern.logging, 'basicConfig')
```

I tried the following commands as well:

* tox -e py39 -- ./tests/test_modern.py
* tox -e py39 -- pyclean/tests/test_modern.py
* tox -e py39 -- test_modern.py

I also tried various combinations of the changedir and basetemp and config values in tox.ini, e.g.:

```
[testenv]
description = Unit tests
deps =
    cli-test-helpers
    py27: mock
    pypy2: mock
    pytest
changedir = tests
commands = pytest --basetemp="{envtmpdir}" {posargs}
```

What am I doing wrong here? It's obviously not a big deal but would be nice to run only the tests I'm changing.

**Comment by bittner** [comment]
Sorry for the inconvenience. That should be easier to do. I'll take a look at it.

**Comment by bittner** [comment]
Thank you for reporting this issue, @dave-kennedy! :100: :+1: 

This should be fixed now on the `master` branch.

**Comment by dave-kennedy** [comment]
Wow, you're fast. Thanks!
