### ISSUE TITLE
Add -d/--delete-empty option to pyclean

### ISSUE THREAD

**Issue by rgeoghegan** [bittner/pyclean#32]
The `--delete-empty` option would only remove `.pyc` (in python2) or `__pycache__` (in python3) files in directories with no other files. And then it would **delete that now empty directory**.

Let me explain my use case:

If a git commit moves a whole module directory around, git will (as it should) leave behind the old directory with any untracked files (like `.pyc` or `__pycache__`). So let's say I have:

```
./spam/eggs.py
./spam/__pycache__/eggs.cpython-36.pyc
```

, and I checkout an other branch that removes `./spam/eggs.py`. I will now have an "empty" directory with:

```
./spam/__pycache__/eggs.cpython-36.pyc
```

I propose that this new `--delete-empty` option delete the directories `./spam/__pycache__` **and also** `./spam` for me. This is especially insidious in python2, where the stray `.pyc` files are still importable under the old module path name and can cause a lot of confusion.

Does this sound like a good feature for pyclean? I can provide a PR.

**Comment by bittner** [comment]
I would prefer to clean up only those files and directories that were actually created by, or as a side-effect of, some Python tool or tooling process.

Examples:

- build/
- dist/
- sdist/
- eggs/
- .eggs/
- *.egg-info/
- wheels/
- .cache/
- .coverage/
- htmlcov/
- .pytest_cache/
- .tox/

I'm a bit worried that your use case doesn't exactly match that premise. It would make the cleanup too generic, not strictly related to Python. IIUC, your use case is related to Git. You could install a Git hook that runs `pyclean` after each of the activities you find critical.

What do you think?

**Comment by rgeoghegan** [comment]
That is fair enough as a reason. I think I'll fix my use-case in another tool.

**Comment by bittner** [comment]
Note that it might be a valid use case (and helpful feature) to add an option to install a Git hook for cleaning up (certain paths of) your project. Maybe you want to give that a shot? :thinking:
