### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Gabriel-p** [bittner/pyclean#33]
Tried `pyclean 1.0` on a project folder but it does nothing. It used to work, not it stopped.

```
$ pyclean -v .
D: pyclean:84: argv: ['/usr/bin/pyclean', '-v', '.']
D: pyclean:85: options: {'verbose': True, 'package': None}
D: pyclean:86: args: ['.']
I: pyclean:104: cleaning directories: ['.']
I: pyclean:67: removed files: 0
```

**Comment by bittner** [comment]
You're most likely on Debian, which has the original `pyclean` script installed for Python 2.7, which comes with e.g. the `python-minimal` Debian package (see [related information in our README](https://github.com/bittner/pyclean#debian)).

If you have _this project's_ Python package installed you should be able to run it like this to circumvent ambiguities:
```console
python -m pyclean
```
... with the Python interpreter you used to install the package, obviously.

I hope that helps.
