### ISSUE TITLE
Empty __pycache__ directory not removed

### ISSUE THREAD

**Issue by bendikro** [bittner/pyclean#34]
Is it intended that empty `__pycache__` directories aren't removed?
```
$ mkdir -p clean_dir/__pycache__
$ py3clean clean_dir
$ ls -l clean_dir
__pycache__
```

**Comment by bittner** [comment]
Please try `pyclean` or even more explicitly `python -m pyclean`, and assure yourself you're running the current version 2 of pyclean.

The `py3clean` script is the legacy implementation, which is included for historical completeness. Don't use it unless you explicitly plan to (e.g. on Debian).

Let me know if that helps

**Comment by bendikro** [comment]
> Please try `pyclean` or even more explicitly `python -m pyclean`, and assure yourself you're running the current version 2 of pyclean.
>
> The `py3clean` script is the legacy implementation, which is included for historical completeness. Don't use it unless you explicitly plan to (e.g. on Debian).

Ahh, I see.
The `pyclean` and `py3clean` installed by `python3-minimal` on Ubuntu 18.04 both keep the empty `__pycache__`.
 
> Let me know if that helps

I installed `pyclean` from pypi and that works.

Thanks
