### ISSUE TITLE
Is it possible to remove .ipynb_checkpoints using pyclean?

### ISSUE THREAD

**Issue by RahulDas-dev** [bittner/pyclean#49]
Can pyclean be used to remove **.ipynb checkpoints**? If not, then I'd like to submit a pull request to include the feature.

**Comment by bittner** [comment]
Hi @RahulDas-dev, thank you for your interest in pyclean! Sorry for having you wait for an answer so long. :worried: 

I've just added the long-awaited, long-planned option to clean up other files than bytecode. The implementation is generic and is [based on globbing patterns](https://github.com/bittner/pyclean/blob/main/pyclean/modern.py#L14-L43). `.ipynb_checkpoints` are not covered yet.

So, in that vein, good news! If you would like to submit a PR you're more than welcome! :+1:

**Comment by RahulDas-dev** [comment]
Thanks , I will submit a pr.

**Comment by bittner** [comment]
@RahulDas-dev I'm taking the freedom to start a PR on your behalf, because I would like to include the feature you requested in the release I want to push to PyPI tonight. I hope you don't mind. :worried:

**Comment by bittner** [comment]
[PyClean 2.4.0](https://pypi.org/project/pyclean/2.4.0/) is now published on PyPI. :rocket: 

Please, take a look and let us know whether it does what you intended. You may trigger a notebook checkpoints cleanup like this:

```console
pyclean . --debris=jupyter
```

or

```console
pyclean . --debris=all
```

If there's anything you'd want to change feel free to open a PR for a fix.

Thank you! :100:

**Comment by RahulDas-dev** [comment]
okay
