### ISSUE TITLE
It fails to work after a fresh install

### ISSUE THREAD

**Issue by AllanDaemon** [bittner/pyclean#61]
After a fresh install, I tried to run it, but it gave me errors from the find command.

An example here:
https://asciinema.org/a/PpU8SmKIDmAvOQw3C1R1dZ3sX

```sh
$ pyclean --help | head  
Usage: find [-H] [-L] [-P] [-Olevel] [-D debugopts] [path...] [expression]

default path is the current directory; default expression is -print
expression may consist of: operators, options, tests, and actions:
operators (decreasing precedence; -and is implicit where no others are given):
      ( EXPR )   ! EXPR   -not EXPR   EXPR1 -a EXPR2   EXPR1 -and EXPR2
      EXPR1 -o EXPR2   EXPR1 -or EXPR2   EXPR1 , EXPR2
positional options (always true): -daystart -follow -regextype

normal options (always true, specified before other expressions):
$ pyclean -h
find: unknown predicate `-h'
find: unknown predicate `-h'
find: unknown predicate `-h'
find: unknown predicate `-h'
```
More info:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

$ whereis pyclean
pyclean: /data/_ubuntu/tools/miniconda3/bin/pyclean
```

**Comment by bittner** [comment]
Hmm, interesting. According to your screencast, you installed the current version of PyClean. However, what you execute is not `pyclean`. The output says, `find`. It looks like you have some aliases in place.

Can you try the following commands, please, and paste their output?

```console
alias pyclean
```
```console
which pyclean
```
```console
python -m site
```
```console
echo $PATH
```
```console
python -m pyclean --help
```
The problem, most likely, is that the scripts Python installs are not on your `PATH`. This is not specific to PyClean, it's for all Python packages that install [entrypoint scripts](https://github.com/bittner/pyclean/blob/main/setup.py#L49-L55).

You might need to add `~/.local/bin` to your `PATH` to make it all work in general.

**Comment by AllanDaemon** [comment]
Thanks. Indeed, it was a redefinition:

```sh
$ which pyclean
pyclean () {
        find "${@:-.}" -type f -name "*.py[co]" -delete
        find "${@:-.}" -type d -name "__pycache__" -delete
        find "${@:-.}" -depth -type d -name ".mypy_cache" -exec rm -r "{}" +
        find "${@:-.}" -depth -type d -name ".pytest_cache" -exec rm -r "{}" +
}
```
It's from a Python plugin from `Oh My Zsh`
https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/python

Thanks for the answer!
