### ISSUE TITLE
pyclean conda-forge

### ISSUE THREAD

**Issue by guru-desh** [bittner/pyclean#78]
Are you planning to upload pyclean to conda-forge so that it can be used within Anaconda (without pip)?

**Comment by bittner** [comment]
I opened a PR on Conda-Forge's staged-recipes repository. :heavy_check_mark: https://github.com/conda-forge/staged-recipes/pull/25337

**Comment by bittner** [comment]
The PR was merged by Conda-Forge, last night. Should be installable using Conda, now. :rocket: 

I'll update the recipe today to reflect the recent release of PyClean v3.0.0 ...

**Comment by guru-desh** [comment]
Thank you so much!
